target 'Kahoot Hackathon' do

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
# https://firebase.google.com/docs/ios/setup#available-pods

end
